repos:
  - repo: local
    hooks:
      - id: isort
        name: isort (Python imports organizer)
        entry: isort
        language: system
        types:
          - python
        files: \.py$

  - repo: local
    hooks:
      - id: ruff
        name: Ruff
        entry: ruff check
        language: system
        types:
          - python
        files: \.py$
